source :rubygems
gem 'rake'
gem 'cucumber'
gem 'rspec'
gem 'watir-webdriver'
gem 'headless'
gem 'page-object'
gem 'nokogiri'
gem 'debugger'
gem 'unicode_utils'
gem 'chromedriver-helper'
gem 'net-http-persistent'
gem 'watir-webdriver-performance', :git => 'git://github.com/roignac/watir-webdriver-performance.git'
